### PR TITLE
Prototype work

### LINKED ISSUE #1004: Messages and edit behavior for review activity in new UI
Stems from #951 
For review mode:
- [ ] After clicking Edit: After clicking Edit, the user should get a confirm message that reads, "Thank you for helping to review this transcription! Submit when you've finished your edits." It should be possible to Save and Submit as if you're in Transcribe mode from here. If the user Submits the transcription to be (re-)reviewed, the confirm message should be "Thanks! Want to keep reviewing?" - and then provide a button that when clicked takes them to the next page to review.
- [ ] After clicking Accept: the message at the bottom should be "Thanks! Want to keep reviewing?" and then provide a button that when clicked takes them to the next page to review (button text TBD)

### LINKED ISSUE #1084: Research and diagnose "Unable to save" issue in prototype
**What behavior did you observe? Please describe the bug**
We've seen/heard feedback about this. 

1 - during the Congressional Scavenger hunt event. Roughly about 10 people at any given time were using the prototype during a two-hour span. Many were getting "Unable to save your work." 

2 - A user also emailed about it. Here is the message below: 

> Carefully, I thought about how to proceed, remembering your advice.
>
> At first, I did not click "edit", I went directly to the interface link.  When I could not interact with the page I returned to page 55.  I made no changes to the page, just clicked "edit", then followed the link to the new interface.  When I clicked "edit" on this page, this message appeared:
> 
> "Unable to save your work This transcription has already been reviewed."
> 
>  Now, not only am I unable to continue on this interface page, when I closed this interface page and returned to page 55, I am UNABLE TO OPEN THIS PAGE NOW, the "edit" button does nothing.
> 
> There is definitely a hitch in my maneuvering between these two.   I shall abandon your new interface for now.  I have no problems with your site otherwise and thoroughly enjoy the work I am doing.  I have been honestly moved by the stories I am reading.  And I enjoy being able to still use all my book publishing skills.

A few users will be typing full pages and then come to this message. This reads to me that they are all trying to work on the same asset and the indicators that help them know that are not clear.

### PR DESCRIPTION
**Pull request by rstorey**
Closes #1084 and closes #1004 (when complete)

### CODE REVIEW

**Comment by rstorey** [comment]
Need to silence / ticket / fix:

concordia/static/js/action-app/components.js
  202:9   error  Unexpected 'todo' comment   unicorn/expiring-todo-comments
  299:13  error  Unexpected 'fixme' comment  unicorn/expiring-todo-comments
  324:9   error  Unexpected 'todo' comment   unicorn/expiring-todo-comments
  816:9   error  Unexpected 'fixme' comment  unicorn/expiring-todo-comments

concordia/static/js/action-app/index.js
   236:26  error  Move arrow function to the outer scope  unicorn/consistent-function-scoping
   446:21  error  Unexpected 'todo' comment               unicorn/expiring-todo-comments
   482:21  error  Unexpected 'todo' comment               unicorn/expiring-todo-comments
  1046:9   error  Unexpected 'todo' comment               unicorn/expiring-todo-comments
  1137:27  error  Move arrow function to the outer scope  unicorn/consistent-function-scoping
  1220:9   error  Unexpected 'fixme' comment              unicorn/expiring-todo-comments

File: concordia/static/js/action-app/components.js [hunk 1]
```diff
@@ -829,15 +838,23 @@ export class AssetViewer {
         this.submitActionCallback(action, data);
     }
 
-    setMode(newMode) {
-        if (this.mode == newMode) return;
+    setMode(newMode, assetStatus) {
+        if (this.mode == newMode && this.el.dataset.assetStatus == assetStatus)
```
Comment (acdha) [inline concordia/static/js/action-app/components.js]: I'd prefer to wrap this in braces

File: concordia/views.py [hunk 2]
```diff
@@ -1063,6 +1070,7 @@ def submit_transcription(request, *, pk):
         )
 
     transcription.submitted = now()
+    transcription.rejected = None
```
Comment (acdha) [inline concordia/views.py]: Isn't this the default?

File: concordia/static/js/action-app/index.js [hunk 3]
```diff
@@ -218,8 +218,6 @@ export class ActionApp {
             button.classList.toggle('active', button.value == newMode);
         });
 
-        $$('.current-mode').forEach(i => (i.textContent = this.currentMode));
```
Comment (acdha) [inline concordia/static/js/action-app/index.js]: We still have this element in the DOM — should we remove it from `action-app.html` or do we need a separate place to update it?

File: concordia/views.py [hunk 4]
```diff
@@ -1051,9 +1051,16 @@ def submit_transcription(request, *, pk):
     transcription = get_object_or_404(Transcription, pk=pk)
 
     if (
-        transcription.submitted
-        or transcription.asset.transcription_set.filter(supersedes=pk).exists()
-    ):
+        transcription.submitted and not transcription.rejected
+    ) or transcription.asset.transcription_set.filter(supersedes=pk).exists():
```
Comment (acdha) [inline concordia/views.py]: I'm wondering whether it's worth splitting these tests out more since it's a bunch of conditions to parse reading this block.

File: concordia/static/scss/action-app.scss [hunk 5]
```diff
@@ -234,7 +234,7 @@ main {
 
     &[data-mode='review'] {
         #transcriber-column {
-            display: none;
```
Comment (acdha) [inline concordia/static/scss/action-app.scss]: This appears to have drifted between 53b014da3a26a19b8350e91c829289413c90a767 and f1c961bcfb005cffd5125b5c7a0e54c80d2f78e6 and it wasn't immediately obvious to me from the commit message that it was intentional to have both columns displayed in review mode but not transcribe mode.

Comment (rstorey) [reply concordia/static/scss/action-app.scss]: The intent is to have display: flex set for both columns when in review mode but only display: flex for transcribe column in transcribe mode. Even with both columns in review mode set to display: flex, only one displays at a time.

File: concordia/static/js/action-app/index.js (hunk 3 above)
Comment (rstorey) [reply concordia/static/js/action-app/index.js]: I removed it from the DOM.

File: concordia/views.py (hunk 4 above)
Comment (rstorey) [reply concordia/views.py]: Not sure what you mean by that. Can you elaborate?

File: concordia/static/js/action-app/components.js (hunk 1 above)
Comment (rstorey) [reply concordia/static/js/action-app/components.js]: Done

File: concordia/views.py (hunk 4 above)
Comment (acdha) [reply concordia/views.py]: I was just thinking that the layout was a little ungainly with the big parenthesized expression followed by an `or` and was wondering whether that would be worth assigning a temporary variable for clarity (e.g. `if (transcription.submitted and not transcription.rejected) or is_superseded:`

Comment (rstorey) [reply concordia/views.py]: Oh right on. Yeah that makes sense.
